docs_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    image: python:3.7-slim

  install_script:
    - apt update && apt install make
    - pip install --upgrade-strategy eager -U -r requirements-docs.txt
    - pip install -e .

  script:
    - make -C docs/ html

lint_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    image: python:3.7-slim

  install_script:
    - pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - pip install --upgrade-strategy eager -U -r requirements-lint.txt
    - pip install -e .

  script:
    - python3 --version
    - pip list
    - ./lint.sh



FreeBSD_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  env:
    matrix:
      - PYTHON: 3.6
      - PYTHON: 3.7
  install_script:
    - PYVER=`echo $PYTHON | tr -d '.'`
    - PYPKG=py${PYVER}
    - PY=python${PYTHON}
    - pkg install -y bash python${PYVER} ${PYPKG}-setuptools
    - ${PY} -m ensurepip
    - ${PY} -m pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - ${PY} -m pip install -e .

  script:
    - export PY=python${PYTHON}
    - ${PY} --version
    - ${PY} -m pip list
    - ./test.sh

Linux_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  container:
    matrix:
      - image: python:3.6-slim
      - image: python:3.7-slim
      - image: python:3.8-rc-slim
      - image: pypy:3.6-slim

  install_script:
    - pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - pip install -e .

  script:
    - command -v pypy3 >/dev/null && export PY=pypy3
    - ${PY-python3} --version
    - pip list
    - ./test.sh

macOS_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  osx_instance:
    image: mojave-base
  env:
    PATH: ${HOME}/.pyenv/shims:${PATH}
    matrix:
      - PYTHON: 3.6.8
      - PYTHON: 3.7.2
  install_script:
    # Per the pyenv homebrew recommendations.
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    - sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
    - brew install openssl readline pyenv
    - pyenv install ${PYTHON}
    - pyenv global ${PYTHON}
    - pyenv rehash
    - pip install --upgrade-strategy eager -U pip wheel setuptools
    - pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - pip install -e .

  script:
    - python3 --version
    - pip list
    - ./test.sh

Windows_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  windows_container:
    os_version: 2019
    matrix:
      - image: python:3.6-windowsservercore-1809
      - image: python:3.7-windowsservercore-1809
      - image: python:3.8-rc-windowsservercore-1809

  install_script:
    - C:\Python\python.exe -m pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - C:\Python\python.exe -m pip install -e .

  script:
    - C:\Python\python.exe --version
    - C:\Python\python.exe -m pip list

    - C:\Python\python.exe -m doctest README.md ppb_vector/__init__.py
    - C:\Python\python.exe -m pytest --hypothesis-profile ci
