addons:
  apt:
    packages:
      - realpath

sudo: no
language: python
matrix:
    fast_finish: yes
    include:
        # CPython builds
        - os: linux
          python: 3.6
        - os: linux
          language: generic
          env: PYTHON="3.7"
        - os: linux
          python: nightly

        # PyPy builds
        - os: linux
          language: generic
          env: PYTHON="pypy-py3.6"

    allow_failures:
        - python: "nightly"
        - env: PYTHON="pypy-py3.6"

cache:
    directories:
      - $HOME/.cache/pip
      - .hypothesis

before_install:
  - source ./.ci/install-python.sh

install:
  - pip install -U pip wheel setuptools
  - pip install -e .;
  - # Do not install mypy during pypy builds
    '[[ ! "$PYTHON" =~ pypy-* ]] || sed -i "/^mypy/d" dev-requirements.txt'
  - pip install -U -r dev-requirements.txt;
  - pip list

script:
  - pytest --hypothesis-profile ci
  - '[[ "$PYTHON" =~ pypy-* ]] || mypy ppb_vector tests'
  - python -m doctest README.md
