language: python
matrix:
    fast_finish: yes
    include:
        # CPython builds
        - os: linux
          python: 3.6
        - os: linux
          language: generic
          env: PYTHON="3.7"
        - os: linux
          python: nightly

        # PyPy builds
        - os: linux
          language: generic
          env: PYTHON="pypy-py3.6"

    allow_failures:
        - python: "nightly"
        - env: PYTHON="pypy-py3.6"

cache:
    directories:
      - $HOME/.cache/pip
      - .hypothesis

before_install:
  - source ./.ci/install-python.sh

install:
  - pip install -e .;
  - pip install -r dev-requirements.txt;
  
script:
  - pytest --hypothesis-profile ci
  - mypy ppb_vector tests
  - python -m doctest README.md
