addons:
  apt:
    packages:
      - realpath

sudo: no
language: python
matrix:
    fast_finish: yes
    include:
        # CPython builds
        - os: linux
          python: 3.6
        - os: linux
          language: generic
          env: PYTHON="3.7"
        - os: linux
          python: nightly

        # PyPy builds
        - os: linux
          language: generic
          env: PYTHON="pypy-py3.6"

    allow_failures:
        - python: "nightly"
        - env: PYTHON="pypy-py3.6"

cache:
    directories:
      - $HOME/.cache/pip
      - .hypothesis

before_install:
  - source ./.ci/install-python.sh
  - export TRAVIS_OS_NAME PYTHON

install:
  - pip install --upgrade-strategy eager -U pip wheel setuptools
  - pip install -e .;
  - pip install --upgrade-strategy eager -U -r dev-requirements.txt
  - # Lints aren't run under pypy
    '[[ "$PYTHON" =~ pypy-* ]] || pip install --upgrade-strategy eager -U -r lint-requirements.txt'
  - pip list

script:
  - PY=python ./lint.sh
  - PY=python ./test.sh
