status = [
  "docs",
  "FreeBSD PYTHON:3.6",
  "FreeBSD PYTHON:3.7",
  "lint",
  "Linux IMAGE:python:3.6-slim container:python:3.6-slim",
  "Linux IMAGE:python:3.7-slim container:python:3.7-slim",
  "Windows IMAGE:python:3.6-windowsservercore-1809 container:python:3.6-windowsservercore-1809",
  "Windows IMAGE:python:3.7-windowsservercore-1809 container:python:3.7-windowsservercore-1809",
  "macOS PYTHON:3.6.8",
  "macOS PYTHON:3.7.2",
]
