name: Bors Labeller

on: [check_run, pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    
    steps:
    - uses: ppb/actions-bors@master
      if: github.event_name == 'check_run' && github.event.check_run.app.name != 'Cirrus CI'
      with:
        foo: bar
        spam: eggs
