name: Bors Labeller

on: [check_run, check_suite, pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    
    steps:
    - uses: ppb/actions-bors@master
      with:
        foo: bar
        spam: eggs
